apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
        - name: image-service
          image: imageservice-image-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://root:example@mongodb-service:27017/image_service_db?authSource=admin
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: image-service
spec:
  selector:
    app: image-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
